/* RobTop — словари оболочки (core). Регистрируются в движке i18n.
   Здесь: общие слова, главный экран, HUD, имена плиток, настройки, магазин,
   ошибки (включая коды ошибок PHP-бэкенда). Строки модулей — в их module.js.

   Добавить язык: скопировать блок en и перевести; добавить код локали в core/i18n.js. */
(function (RT) {
  "use strict";
  if (!RT || !RT.i18n) return;

  RT.i18n.add({
    /* =================== ENGLISH (default) =================== */
    en: {
      common: {
        cancel: "Cancel", close: "Close", save: "Save", delete: "Delete",
        yes: "Yes", no: "No", done: "Done", undo: "Undo", enter: "Enter",
        demo: "demo", removed: "Removed", failed: "Couldn't do that",
        back: "Back", home: "Home", confirmTitle: "Confirm?"
      },
      home: { tagline: "Choose an app", soonSep: "Coming soon" },
      reorder: {
        hint: "Drag to reorder",
        hidden: "Hidden", hide: "Hide", show: "Show",
        lastNo: "At least one app must stay visible"
      },
      hud: { apps: "apps", available: "available" },
      nav: { apps: "Apps", bank: "Bank", chat: "Chat", notifications: "Alerts", settings: "Settings" },
      sync: { newVer: "Update available", reload: "Update" },
      tile: {
        status: { open: "Open", soon: "Soon" },
        soonToast: "{name}: soon!",
        wishlist: "Wishlist", reverse: "Words Backwards", mood: "Mood of the Day",
        teeth: "Toothbrushing Timer", guess: "Guess the Number", names: "Funny Names",
        days: "Day Counter", find: "Find the Object", museum: "Home Museum",
        rating: "Day Rating", friends: "Friends", lost: "Lost & Found", walk: "Dog Walk", snake: "Snake", bank: "Piggy Bank", shop: "Shop", chat: "Chat", seabattle: "Sea Battle", dice: "Dice"
      },
      settings: {
        open: "Settings", title: "Settings", language: "Language",
        manageApps: "Manage apps", theme: "Theme"
      },
      theme: { neon: "Neon", tilley: "Tilley Live" },
      family: {
        title: "Family",
        empty: "No children yet.",
        addChild: "Add a child", addHint: "Only a nickname. No email for children.",
        nickPh: "Child's nickname", addBtn: "Create",
        created: "{name} created. First sign-in password: {pass}",
        nickTaken: "This nickname is taken",
        invite: "Invite second parent", inviteHint: "They get parent rights. Enter their email.",
        inviteBtn: "Create invitation",
        linkHint: "Send this link. It works once and expires in 7 days.",
        copy: "Copy link", copied: "Copied",
        resetPass: "Reset password", resetConfirm: "Reset {name}'s password? They will get a new one-time password.",
        resetDone: "{name}: one-time password is {pass}, they will set a new one at sign-in",
        block: "Block account", unblock: "Unblock account",
        blockConfirm: "Block {name}? They won't be able to sign in. Data is kept.",
        unblockConfirm: "Unblock {name}?",
        blockDone: "{name} is blocked", unblockDone: "{name} can sign in again",
        blocked: "blocked",
        parents: "Parents", kids: "Children", guest: "guest", roleOwner: "owner", you: "you",
        transfer: "Hand over to their parent",
        transferHint: "Enter the real parent's email. They will register and get parental rights for this child; your temporary guardianship will end.",
        invites: "Invitations", invitesEmpty: "No sent invitations.",
        revoke: "Revoke", revoked: "Invitation revoked",
        resend: "New link", resendDone: "Here is a fresh link:",
        invType: { co_parent: "second parent", child_to_child: "friend", transfer_child: "child handover", child_invite_parent: "parent invitation" },
        st: { pending: "pending", accepted: "accepted", revoked: "revoked", expired: "expired" },
        share: "Public wishlist", shareOn: "on", shareOff: "off",
        shareConfirmOn: "Open {name}'s wishlist to anyone with the link (photos included) and allow sharing with RobTop users?",
        shareConfirmOff: "Close {name}'s wishlist? The link and all granted accesses stop working right away.",
        shareOnDone: "Wishlist sharing is on", shareOffDone: "Wishlist sharing is off"
      },
      myparent: {
        title: "My parent",
        managed: "Your parent manages your account and family.",
        hint: "You have no parent in the app yet. Enter your parent's email — they will get an invitation and become your parent here.",
        inviteBtn: "Invite my parent", sent: "Invitation sent! 📨",
        pendingHint: "The invitation has been sent to your parent. You can revoke it and send a new one.",
        revoked: "Invitation revoked",
        conflict: "Invitation already exists, or you already have a parent"
      },
      shared: {
        title: "Shared with me",
        empty: "No one has shared a wishlist with you yet."
      },
      friend: {
        title: "Friends",
        hint: "You can invite a friend — they'll get their own RobTop.",
        invite: "Invite a friend",
        sheetHint: "Your friend will pick a nickname (never a real name!) and get their own RobTop. Until their parent joins, your parent looks after their account.",
        makeLink: "Create link",
        sendHint: "Send this link to your friend. It works for 7 days."
      },
      helpdesk: {
        title: "Help",
        report: "Report a problem",
        hint: "Tell us what went wrong. The RobTop team will read it and reply right here in the app.",
        ph: "What happened?",
        send: "Send", sent: "Sent! The reply will appear in Settings → Help",
        tooShort: "Tell us a little more",
        tooMany: "Too many reports — please try later",
        mine: "My reports:", newReply: "new reply",
        stOpen: "open", stClosed: "closed",
        threadTitle: "My report",
        you: "Me", support: "RobTop team",
        replyPh: "Write a reply…", reply: "Reply",
        reopenHint: "Your reply will reopen this report.",
        solve: "Solved ✓", solveConfirm: "Mark the problem as solved?",
        solved: "Marked as solved"
      },
      reg: {
        link: "I am a new parent — create a family",
        nickPh: "Your nickname",
        title: "Create your family",
        hint: "Parents sign up with email. You'll add children inside, they need only a nickname.",
        btn: "Create family",
        fail: "Couldn't create: check email and nickname (maybe taken)"
      },
      lock: { hint: "Sign in to continue", title: "Who is signing in?" },
      account: {
        title: "Account",
        loading: "Checking who is signed in…",
        loginHint: "Parents sign in with email, children with a nickname.",
        loginPh: "Email or nickname", passPh: "Password",
        signIn: "Sign in", signOut: "Sign out",
        roleParent: "parent/guardian", roleChild: "child",
        badLogin: "Wrong login or password",
        changeTitle: "Set a new password",
        changeHint: "You signed in with a one-time password. Set your own password to continue.",
        newPassPh: "New password", saveCont: "Save and continue",
        weakPass: "At least 4 characters",
        demoNote: "Sign-in works in the server version of the app.",
        welcome: "Welcome, {name}!", signedOut: "Signed out",
        guestNote: "Without sign-in the app runs in family mode.",
        forgot: "Forgot password?",
        forgotHint: "For parents only: a child's password is reset by their parent. Enter your email — we'll send a reset link.",
        forgotSend: "Send the link", forgotSent: "If this email is registered, the link has been sent.",
        deviceList: "On this device",
        addAccount: "Add account",
        addHint: "Sign in once — the account will stay on this device for quick switching.",
        orPassword: "Or sign in with a password:",
        switchGone: "This account is no longer available — sign in with the password",
        removeDev: "Remove from this device",
        removeConfirm: "Remove {name} from this device? You'll need the password to add it back. Data is kept.",
        removedDev: "{name} removed from this device"
      },
      store: {
        title: "Apps", adminNote: "App management is for a parent.",
        installed: "Installed", installApp: "Install an app",
        pickBundle: "📦 Pick a bundle (.robtop.json)",
        up: "Up", down: "Down", remove: "Remove", toggle: "On / off",
        srcInstalled: "installed", srcBuiltin: "built-in", soonSuffix: " · soon",
        installedToast: "Installed: {name}",
        uninstallTitle: "Remove app?", uninstallText: "Data and events will be kept."
      },
      err: {
        install_failed: "Couldn't install", install_error: "Install error",
        bundle_not_json: "Broken bundle (not JSON)",
        bundle_no_manifest: "Bundle has no manifest/files",
        bad_id: "Invalid app id",
        server_code_denied: "Server code in a bundle is not allowed",
        module_load: "Module didn't load", module_error: "Module error",
        module_open: "Couldn't open “{name}”",
        config_missing: "config.php not found",
        db_failed: "Couldn't connect to the database",
        not_image: "This is not an image",
        expected_image: "An image is expected (png/jpg/webp/gif)",
        corrupt_data: "Corrupted data",
        file_too_big: "File is too big",
        save_failed: "Couldn't save the file",
        need_manifest: "manifest and files are required",
        reserved_id: "Reserved id",
        cant_replace_native: "Can't replace a built-in module",
        bad_filename: "Bad file name: {name}",
        bad_type: "Disallowed type: {name}",
        bundle_too_big: "Bundle is too big",
        no_module_js: "Bundle has no module.js",
        no_apps_dir: "No permission for the apps folder",
        write_failed: "Couldn't write {name}",
        cant_uninstall_native: "Can't remove a built-in module"
      }
    },

    /* =================== РУССКИЙ =================== */
    ru: {
      common: {
        cancel: "Отмена", close: "Закрыть", save: "Сохранить", delete: "Удалить",
        yes: "Да", no: "Нет", done: "Готово", undo: "Отменить", enter: "Войти",
        demo: "демо", removed: "Удалено", failed: "Не удалось",
        back: "Назад", home: "Домой", confirmTitle: "Подтвердить?"
      },
      home: { tagline: "Выбери приложение", soonSep: "Скоро будут" },
      reorder: {
        hint: "Перетащи, чтобы поменять порядок",
        hidden: "Скрытые", hide: "Скрыть", show: "Показать",
        lastNo: "Хотя бы одно приложение должно остаться"
      },
      hud: { apps: "приложений", available: "доступно" },
      nav: { apps: "Приложения", bank: "Копилка", chat: "Чат", notifications: "Оповещения", settings: "Настройки" },
      sync: { newVer: "Доступно обновление", reload: "Обновить" },
      tile: {
        status: { open: "Открыть", soon: "Скоро" },
        soonToast: "{name}: скоро!",
        wishlist: "Виш-лист", reverse: "Слова наоборот", mood: "Настроение дня",
        teeth: "Таймер чистки зубов", guess: "Угадай число", names: "Смешные имена",
        days: "Счётчик дней", find: "Найти предмет", museum: "Домашний музей",
        rating: "Оценка дня", friends: "Друзья", lost: "Бюро находок", walk: "Прогулка", snake: "Змейка", bank: "Копилка", shop: "Магазин", chat: "Чат", seabattle: "Морской бой", dice: "Кубик"
      },
      settings: {
        open: "Настройки", title: "Настройки", language: "Язык",
        manageApps: "Управление приложениями", theme: "Оформление"
      },
      theme: { neon: "Неон", tilley: "Tilley Live" },
      family: {
        title: "Семья",
        empty: "Детей пока нет.",
        addChild: "Добавить ребёнка", addHint: "Только никнейм. Email детям не нужен.",
        nickPh: "Никнейм ребёнка", addBtn: "Создать",
        created: "{name}: пароль для первого входа {pass}",
        nickTaken: "Этот никнейм занят",
        invite: "Пригласить второго родителя", inviteHint: "Он получит права родителя. Укажите его email.",
        inviteBtn: "Создать приглашение",
        linkHint: "Отправьте эту ссылку. Работает один раз, действует 7 дней.",
        copy: "Копировать ссылку", copied: "Скопировано",
        resetPass: "Сбросить пароль", resetConfirm: "Сбросить пароль {name}? Будет выдан новый одноразовый пароль.",
        resetDone: "{name}: одноразовый пароль {pass}, новый он задаст при входе",
        block: "Заблокировать аккаунт", unblock: "Разблокировать аккаунт",
        blockConfirm: "Заблокировать {name}? Он не сможет войти. Данные сохранятся.",
        unblockConfirm: "Разблокировать {name}?",
        blockDone: "{name} заблокирован", unblockDone: "{name} снова может войти",
        blocked: "заблокирован",
        parents: "Родители", kids: "Дети", guest: "гость", roleOwner: "владелец", you: "вы",
        transfer: "Передать родителю",
        transferHint: "Email настоящего родителя: он зарегистрируется и получит права на этого ребёнка, ваша временная опека завершится.",
        invites: "Приглашения", invitesEmpty: "Отправленных приглашений нет.",
        revoke: "Отозвать", revoked: "Приглашение отозвано",
        resend: "Новая ссылка", resendDone: "Вот свежая ссылка:",
        invType: { co_parent: "второй родитель", child_to_child: "друг", transfer_child: "передача ребёнка", child_invite_parent: "приглашение родителя" },
        st: { pending: "ждёт", accepted: "принято", revoked: "отозвано", expired: "истекло" },
        share: "Публичный виш-лист", shareOn: "включён", shareOff: "выключен",
        shareConfirmOn: "Открыть виш-лист {name} всем, у кого есть ссылка (включая фото), и разрешить делиться с пользователями RobTop?",
        shareConfirmOff: "Закрыть виш-лист {name}? Ссылка и все выданные доступы сразу перестанут работать.",
        shareOnDone: "Шаринг виш-листа включён", shareOffDone: "Шаринг виш-листа выключен"
      },
      myparent: {
        title: "Мой родитель",
        managed: "Твоим аккаунтом и семьёй управляет родитель.",
        hint: "У тебя пока нет родителя в приложении. Введи email своего родителя — он получит приглашение и станет твоим родителем здесь.",
        inviteBtn: "Пригласить родителя", sent: "Приглашение отправлено! 📨",
        pendingHint: "Приглашение родителю отправлено. Можно отозвать его и отправить новое.",
        revoked: "Приглашение отозвано",
        conflict: "Приглашение уже отправлено, или родитель уже есть"
      },
      shared: {
        title: "Поделились со мной",
        empty: "Пока никто не поделился с вами виш-листом."
      },
      friend: {
        title: "Друзья",
        hint: "Можно позвать друга — у него появится свой RobTop.",
        invite: "Позвать друга",
        sheetHint: "Друг придумает себе никнейм (не настоящее имя!) и получит свой RobTop. Пока его родитель не присоединился, за его аккаунтом присматривает твой родитель.",
        makeLink: "Создать ссылку",
        sendHint: "Отправь эту ссылку другу. Она работает 7 дней."
      },
      helpdesk: {
        title: "Помощь",
        report: "Сообщить о проблеме",
        hint: "Расскажи, что пошло не так. Команда RobTop прочитает и ответит прямо здесь, в приложении.",
        ph: "Что случилось?",
        send: "Отправить", sent: "Отправлено! Ответ появится в Настройках → Помощь",
        tooShort: "Расскажи чуть подробнее",
        tooMany: "Слишком много обращений — попробуй позже",
        mine: "Мои обращения:", newReply: "новый ответ",
        stOpen: "открыт", stClosed: "закрыт",
        threadTitle: "Моё обращение",
        you: "Я", support: "Команда RobTop",
        replyPh: "Написать ответ…", reply: "Ответить",
        reopenHint: "Ответ снова откроет обращение.",
        solve: "Решено ✓", solveConfirm: "Отметить проблему решённой?",
        solved: "Отмечено решённым"
      },
      reg: {
        link: "Я новый родитель — создать семью",
        nickPh: "Ваш никнейм",
        title: "Создайте семью",
        hint: "Родители регистрируются по email. Детей добавите внутри, им нужен только никнейм.",
        btn: "Создать семью",
        fail: "Не удалось: проверьте email и никнейм (возможно, заняты)"
      },
      lock: { hint: "Войдите, чтобы продолжить", title: "Кто входит?" },
      account: {
        title: "Аккаунт",
        loading: "Проверяем, кто вошёл…",
        loginHint: "Родители входят по email, дети по никнейму.",
        loginPh: "Email или никнейм", passPh: "Пароль",
        signIn: "Войти", signOut: "Выйти",
        roleParent: "родитель/опекун", roleChild: "ребёнок",
        badLogin: "Неверный логин или пароль",
        changeTitle: "Задай новый пароль",
        changeHint: "Вход был по одноразовому паролю. Придумай свой пароль, чтобы продолжить.",
        newPassPh: "Новый пароль", saveCont: "Сохранить и продолжить",
        weakPass: "Минимум 4 символа",
        demoNote: "Вход работает в серверной версии приложения.",
        welcome: "Привет, {name}!", signedOut: "Вы вышли",
        guestNote: "Без входа приложение работает в семейном режиме.",
        forgot: "Забыли пароль?",
        forgotHint: "Только для родителя: ребёнку пароль сбрасывает родитель. Введите email — пришлём ссылку для смены пароля.",
        forgotSend: "Отправить ссылку", forgotSent: "Если такой email зарегистрирован, ссылка отправлена.",
        deviceList: "На этом устройстве",
        addAccount: "Добавить аккаунт",
        addHint: "Войдите один раз — аккаунт останется на устройстве для быстрого переключения.",
        orPassword: "Или войдите по паролю:",
        switchGone: "Этот аккаунт больше недоступен — войдите по паролю",
        removeDev: "Убрать с этого устройства",
        removeConfirm: "Убрать {name} с этого устройства? Чтобы вернуть, понадобится пароль. Данные сохранятся.",
        removedDev: "{name} убран с этого устройства"
      },
      store: {
        title: "Приложения", adminNote: "Управление приложениями — для родителя.",
        installed: "Установленные", installApp: "Установить приложение",
        pickBundle: "📦 Выбрать бандл (.robtop.json)",
        up: "Выше", down: "Ниже", remove: "Удалить", toggle: "Вкл / выкл",
        srcInstalled: "установлено", srcBuiltin: "встроено", soonSuffix: " · скоро",
        installedToast: "Установлено: {name}",
        uninstallTitle: "Удалить приложение?", uninstallText: "Данные и события сохранятся."
      },
      err: {
        install_failed: "Не удалось установить", install_error: "Ошибка установки",
        bundle_not_json: "Битый бандл (не JSON)",
        bundle_no_manifest: "В бандле нет manifest/files",
        bad_id: "Неверный id приложения",
        server_code_denied: "Серверный код в бандле запрещён",
        module_load: "Модуль не загрузился", module_error: "Ошибка модуля",
        module_open: "Не удалось открыть «{name}»",
        config_missing: "config.php не найден",
        db_failed: "Не удалось подключиться к базе данных",
        not_image: "Это не изображение",
        expected_image: "Ожидается картинка (png/jpg/webp/gif)",
        corrupt_data: "Повреждённые данные",
        file_too_big: "Файл слишком большой",
        save_failed: "Не удалось сохранить файл",
        need_manifest: "Нужны manifest и files",
        reserved_id: "Зарезервированный id",
        cant_replace_native: "Нельзя заменить встроенный модуль",
        bad_filename: "Плохое имя файла: {name}",
        bad_type: "Недопустимый тип: {name}",
        bundle_too_big: "Бандл слишком большой",
        no_module_js: "В бандле нет module.js",
        no_apps_dir: "Нет прав на папку apps",
        write_failed: "Не удалось записать {name}",
        cant_uninstall_native: "Нельзя удалить встроенный модуль"
      }
    },

    /* =================== LATVIEŠU =================== */
    lv: {
      common: {
        cancel: "Atcelt", close: "Aizvērt", save: "Saglabāt", delete: "Dzēst",
        yes: "Jā", no: "Nē", done: "Gatavs", undo: "Atsaukt", enter: "Ienākt",
        demo: "demo", removed: "Izdzēsts", failed: "Neizdevās",
        back: "Atpakaļ", home: "Mājas", confirmTitle: "Apstiprināt?"
      },
      home: { tagline: "Izvēlies lietotni", soonSep: "Drīz būs" },
      reorder: {
        hint: "Velc, lai mainītu secību",
        hidden: "Paslēptās", hide: "Paslēpt", show: "Parādīt",
        lastNo: "Vismaz vienai lietotnei jāpaliek redzamai"
      },
      hud: { apps: "lietotnes", available: "pieejamas" },
      nav: { apps: "Lietotnes", bank: "Krājkase", chat: "Čats", notifications: "Paziņojumi", settings: "Iestatījumi" },
      sync: { newVer: "Pieejams atjauninājums", reload: "Atjaunināt" },
      tile: {
        status: { open: "Atvērt", soon: "Drīz" },
        soonToast: "{name}: drīz!",
        wishlist: "Vēlmju saraksts", reverse: "Vārdi otrādi", mood: "Dienas garastāvoklis",
        teeth: "Zobu tīrīšanas taimeris", guess: "Uzmini skaitli", names: "Smieklīgi vārdi",
        days: "Dienu skaitītājs", find: "Atrodi priekšmetu", museum: "Mājas muzejs",
        rating: "Dienas vērtējums", friends: "Draugi", lost: "Atradumu birojs", walk: "Pastaiga", snake: "Čūska", bank: "Krājkase", shop: "Veikals", chat: "Čats", seabattle: "Jūras kauja", dice: "Kauliņš"
      },
      settings: {
        open: "Iestatījumi", title: "Iestatījumi", language: "Valoda",
        manageApps: "Pārvaldīt lietotnes", theme: "Noformējums"
      },
      theme: { neon: "Neons", tilley: "Tilley Live" },
      family: {
        title: "Ģimene",
        empty: "Bērnu vēl nav.",
        addChild: "Pievienot bērnu", addHint: "Tikai segvārds. Bērniem e-pasts nav vajadzīgs.",
        nickPh: "Bērna segvārds", addBtn: "Izveidot",
        created: "{name}: pirmās pieslēgšanās parole ir {pass}",
        nickTaken: "Šis segvārds ir aizņemts",
        invite: "Ielūgt otru vecāku", inviteHint: "Viņš iegūs vecāka tiesības. Norādiet viņa e-pastu.",
        inviteBtn: "Izveidot ielūgumu",
        linkHint: "Nosūtiet šo saiti. Darbojas vienreiz, derīga 7 dienas.",
        copy: "Kopēt saiti", copied: "Nokopēts",
        resetPass: "Atiestatīt paroli", resetConfirm: "Atiestatīt {name} paroli? Tiks izsniegta jauna vienreizēja parole.",
        resetDone: "{name}: vienreizējā parole ir {pass}, jauno viņš iestatīs pieslēdzoties",
        block: "Bloķēt kontu", unblock: "Atbloķēt kontu",
        blockConfirm: "Bloķēt {name}? Viņš nevarēs pieslēgties. Dati saglabāsies.",
        unblockConfirm: "Atbloķēt {name}?",
        blockDone: "{name} ir bloķēts", unblockDone: "{name} atkal var pieslēgties",
        blocked: "bloķēts",
        parents: "Vecāki", kids: "Bērni", guest: "viesis", roleOwner: "īpašnieks", you: "jūs",
        transfer: "Nodot vecākam",
        transferHint: "Īstā vecāka e-pasts: viņš reģistrēsies un saņems vecāka tiesības uz šo bērnu; jūsu pagaidu aizbildnība beigsies.",
        invites: "Ielūgumi", invitesEmpty: "Nosūtītu ielūgumu nav.",
        revoke: "Atsaukt", revoked: "Ielūgums atsaukts",
        resend: "Jauna saite", resendDone: "Šeit ir jauna saite:",
        invType: { co_parent: "otrs vecāks", child_to_child: "draugs", transfer_child: "bērna nodošana", child_invite_parent: "vecāka ielūgums" },
        st: { pending: "gaida", accepted: "pieņemts", revoked: "atsaukts", expired: "beidzies" },
        share: "Publiskais vēlmju saraksts", shareOn: "ieslēgts", shareOff: "izslēgts",
        shareConfirmOn: "Atvērt {name} vēlmju sarakstu visiem, kam ir saite (ieskaitot foto), un atļaut dalīties ar RobTop lietotājiem?",
        shareConfirmOff: "Aizvērt {name} vēlmju sarakstu? Saite un visas piešķirtās piekļuves uzreiz pārstās darboties.",
        shareOnDone: "Dalīšanās ir ieslēgta", shareOffDone: "Dalīšanās ir izslēgta"
      },
      myparent: {
        title: "Mans vecāks",
        managed: "Tavu kontu un ģimeni pārvalda vecāks.",
        hint: "Tev lietotnē vēl nav vecāka. Ievadi sava vecāka e-pastu — viņš saņems ielūgumu un kļūs par tavu vecāku šeit.",
        inviteBtn: "Uzaicināt vecāku", sent: "Ielūgums nosūtīts! 📨",
        pendingHint: "Ielūgums vecākam ir nosūtīts. Vari to atsaukt un nosūtīt jaunu.",
        revoked: "Ielūgums atsaukts",
        conflict: "Ielūgums jau pastāv, vai vecāks jau ir"
      },
      shared: {
        title: "Ar mani dalījās",
        empty: "Neviens vēl nav padalījies ar vēlmju sarakstu."
      },
      friend: {
        title: "Draugi",
        hint: "Vari uzaicināt draugu — viņam būs savs RobTop.",
        invite: "Uzaicināt draugu",
        sheetHint: "Draugs izdomās sev segvārdu (ne īsto vārdu!) un saņems savu RobTop. Kamēr viņa vecāks nav pievienojies, par viņa kontu rūpējas tavs vecāks.",
        makeLink: "Izveidot saiti",
        sendHint: "Nosūti šo saiti draugam. Tā darbojas 7 dienas."
      },
      helpdesk: {
        title: "Palīdzība",
        report: "Ziņot par problēmu",
        hint: "Pastāsti, kas nogāja greizi. RobTop komanda izlasīs un atbildēs tepat lietotnē.",
        ph: "Kas notika?",
        send: "Nosūtīt", sent: "Nosūtīts! Atbilde parādīsies Iestatījumi → Palīdzība",
        tooShort: "Pastāsti mazliet vairāk",
        tooMany: "Pārāk daudz ziņojumu — pamēģini vēlāk",
        mine: "Mani ziņojumi:", newReply: "jauna atbilde",
        stOpen: "atvērts", stClosed: "aizvērts",
        threadTitle: "Mans ziņojums",
        you: "Es", support: "RobTop komanda",
        replyPh: "Rakstīt atbildi…", reply: "Atbildēt",
        reopenHint: "Atbilde atkal atvērs ziņojumu.",
        solve: "Atrisināts ✓", solveConfirm: "Atzīmēt problēmu kā atrisinātu?",
        solved: "Atzīmēts kā atrisināts"
      },
      reg: {
        link: "Esmu jauns vecāks — izveidot ģimeni",
        nickPh: "Jūsu segvārds",
        title: "Izveidojiet ģimeni",
        hint: "Vecāki reģistrējas ar e-pastu. Bērnus pievienosiet iekšā, viņiem vajag tikai segvārdu.",
        btn: "Izveidot ģimeni",
        fail: "Neizdevās: pārbaudiet e-pastu un segvārdu (iespējams, aizņemti)"
      },
      lock: { hint: "Pieslēdzies, lai turpinātu", title: "Kurš pieslēdzas?" },
      account: {
        title: "Konts",
        loading: "Pārbaudām, kurš ir pieslēdzies…",
        loginHint: "Vecāki pieslēdzas ar e-pastu, bērni ar segvārdu.",
        loginPh: "E-pasts vai segvārds", passPh: "Parole",
        signIn: "Pieslēgties", signOut: "Iziet",
        roleParent: "vecāks/aizbildnis", roleChild: "bērns",
        badLogin: "Nepareizs lietotājvārds vai parole",
        changeTitle: "Iestati jaunu paroli",
        changeHint: "Pieslēgšanās notika ar vienreizēju paroli. Iestati savu paroli, lai turpinātu.",
        newPassPh: "Jauna parole", saveCont: "Saglabāt un turpināt",
        weakPass: "Vismaz 4 rakstzīmes",
        demoNote: "Pieslēgšanās darbojas lietotnes servera versijā.",
        welcome: "Sveiks, {name}!", signedOut: "Jūs izgājāt",
        guestNote: "Bez pieslēgšanās lietotne darbojas ģimenes režīmā.",
        forgot: "Aizmirsi paroli?",
        forgotHint: "Tikai vecākiem: bērna paroli atiestata vecāks. Ievadi e-pastu — atsūtīsim saiti paroles maiņai.",
        forgotSend: "Nosūtīt saiti", forgotSent: "Ja šāds e-pasts ir reģistrēts, saite ir nosūtīta.",
        deviceList: "Šajā ierīcē",
        addAccount: "Pievienot kontu",
        addHint: "Pieslēdzieties vienreiz — konts paliks šajā ierīcē ātrai pārslēgšanai.",
        orPassword: "Vai pieslēdzieties ar paroli:",
        switchGone: "Šis konts vairs nav pieejams — pieslēdzieties ar paroli",
        removeDev: "Noņemt no šīs ierīces",
        removeConfirm: "Noņemt {name} no šīs ierīces? Lai atgrieztu, būs vajadzīga parole. Dati saglabājas.",
        removedDev: "{name} noņemts no šīs ierīces"
      },
      store: {
        title: "Lietotnes", adminNote: "Lietotņu pārvaldība ir vecākiem.",
        installed: "Instalētās", installApp: "Instalēt lietotni",
        pickBundle: "📦 Izvēlies pakotni (.robtop.json)",
        up: "Augšup", down: "Lejup", remove: "Noņemt", toggle: "Ieslēgt / izslēgt",
        srcInstalled: "instalēts", srcBuiltin: "iebūvēts", soonSuffix: " · drīz",
        installedToast: "Instalēts: {name}",
        uninstallTitle: "Noņemt lietotni?", uninstallText: "Dati un notikumi tiks saglabāti."
      },
      err: {
        install_failed: "Neizdevās instalēt", install_error: "Instalēšanas kļūda",
        bundle_not_json: "Bojāta pakotne (nav JSON)",
        bundle_no_manifest: "Pakotnē nav manifest/files",
        bad_id: "Nederīgs lietotnes id",
        server_code_denied: "Servera kods pakotnē nav atļauts",
        module_load: "Modulis neielādējās", module_error: "Moduļa kļūda",
        module_open: "Neizdevās atvērt “{name}”",
        config_missing: "config.php nav atrasts",
        db_failed: "Neizdevās savienoties ar datubāzi",
        not_image: "Šis nav attēls",
        expected_image: "Tiek gaidīts attēls (png/jpg/webp/gif)",
        corrupt_data: "Bojāti dati",
        file_too_big: "Fails ir pārāk liels",
        save_failed: "Neizdevās saglabāt failu",
        need_manifest: "Nepieciešami manifest un files",
        reserved_id: "Rezervēts id",
        cant_replace_native: "Nevar aizstāt iebūvētu moduli",
        bad_filename: "Slikts faila nosaukums: {name}",
        bad_type: "Neatļauts tips: {name}",
        bundle_too_big: "Pakotne ir pārāk liela",
        no_module_js: "Pakotnē nav module.js",
        no_apps_dir: "Nav atļaujas apps mapei",
        write_failed: "Neizdevās ierakstīt {name}",
        cant_uninstall_native: "Nevar noņemt iebūvētu moduli"
      }
    },

    /* =================== DEUTSCH =================== */
    de: {
      common: {
        cancel: "Abbrechen", close: "Schliessen", save: "Speichern", delete: "Loeschen",
        yes: "Ja", no: "Nein", done: "Fertig", undo: "Rueckgaengig", enter: "Anmelden",
        demo: "Demo", removed: "Entfernt", failed: "Das hat nicht geklappt",
        back: "Zurueck", home: "Start", confirmTitle: "Bestaetigen?"
      },
      home: { tagline: "Waehle eine App", soonSep: "Demnaechst" },
      reorder: {
        hint: "Zum Sortieren ziehen",
        hidden: "Ausgeblendet", hide: "Ausblenden", show: "Anzeigen",
        lastNo: "Mindestens eine App muss sichtbar bleiben"
      },
      hud: { apps: "Apps", available: "verfuegbar" },
      nav: { apps: "Apps", bank: "Kasse", chat: "Chat", notifications: "Hinweise", settings: "Einstellungen" },
      sync: { newVer: "Update verfuegbar", reload: "Aktualisieren" },
      tile: {
        status: { open: "Oeffnen", soon: "Bald" },
        soonToast: "{name}: bald!",
        wishlist: "Wunschliste", reverse: "Woerter rueckwaerts", mood: "Stimmung des Tages",
        teeth: "Zaehneputz-Timer", guess: "Zahl erraten", names: "Lustige Namen",
        days: "Tagezaehler", find: "Finde den Gegenstand", museum: "Hausmuseum",
        rating: "Tagesbewertung", friends: "Freunde", lost: "Fundbuero", walk: "Spaziergang", snake: "Snake", bank: "Kasse", shop: "Shop", chat: "Chat", seabattle: "Schiffe versenken", dice: "Wuerfel"
      },
      settings: {
        open: "Einstellungen", title: "Einstellungen", language: "Sprache",
        manageApps: "Apps verwalten", theme: "Design"
      },
      theme: { neon: "Neon", tilley: "Tilley Live" },
      family: {
        title: "Familie",
        empty: "Noch keine Kinder.",
        addChild: "Kind hinzufuegen", addHint: "Nur ein Nickname. Kinder brauchen keine E-Mail.",
        nickPh: "Nickname des Kindes", addBtn: "Erstellen",
        created: "{name} wurde erstellt. Passwort fuer die erste Anmeldung: {pass}",
        nickTaken: "Dieser Nickname ist vergeben",
        invite: "Zweiten Elternteil einladen", inviteHint: "Er oder sie erhaelt Elternrechte. E-Mail eingeben.",
        inviteBtn: "Einladung erstellen",
        linkHint: "Sende diesen Link. Er funktioniert einmal und laeuft nach 7 Tagen ab.",
        copy: "Link kopieren", copied: "Kopiert",
        resetPass: "Passwort zuruecksetzen", resetConfirm: "Passwort fuer {name} zuruecksetzen? Es wird ein neues Einmalpasswort vergeben.",
        resetDone: "{name}: Einmalpasswort ist {pass}; bei der Anmeldung wird ein neues gesetzt",
        block: "Konto sperren", unblock: "Konto entsperren",
        blockConfirm: "{name} sperren? Die Anmeldung ist dann nicht moeglich. Daten bleiben erhalten.",
        unblockConfirm: "{name} entsperren?",
        blockDone: "{name} ist gesperrt", unblockDone: "{name} kann sich wieder anmelden",
        blocked: "gesperrt",
        parents: "Eltern", kids: "Kinder", guest: "Gast", roleOwner: "Besitzer", you: "du",
        transfer: "An echte Eltern uebergeben",
        transferHint: "Gib die E-Mail des echten Elternteils ein. Diese Person registriert sich und erhaelt Elternrechte fuer dieses Kind; deine vorlaeufige Betreuung endet.",
        invites: "Einladungen", invitesEmpty: "Keine gesendeten Einladungen.",
        revoke: "Widerrufen", revoked: "Einladung widerrufen",
        resend: "Neuer Link", resendDone: "Hier ist ein frischer Link:",
        invType: { co_parent: "zweiter Elternteil", child_to_child: "Freund", transfer_child: "Kinduebergabe", child_invite_parent: "Elterneinladung" },
        st: { pending: "ausstehend", accepted: "angenommen", revoked: "widerrufen", expired: "abgelaufen" },
        share: "Oeffentliche Wunschliste", shareOn: "an", shareOff: "aus",
        shareConfirmOn: "Wunschliste von {name} fuer alle mit Link oeffnen (inklusive Fotos) und Teilen mit RobTop-Nutzern erlauben?",
        shareConfirmOff: "Wunschliste von {name} schliessen? Link und alle Freigaben enden sofort.",
        shareOnDone: "Wunschliste ist freigegeben", shareOffDone: "Wunschliste ist geschlossen"
      },
      myparent: {
        title: "Mein Elternteil",
        managed: "Dein Elternteil verwaltet dein Konto und deine Familie.",
        hint: "Du hast in der App noch keinen Elternteil. Gib die E-Mail ein; die Person bekommt eine Einladung und wird hier dein Elternteil.",
        inviteBtn: "Elternteil einladen", sent: "Einladung gesendet! 📨",
        pendingHint: "Die Einladung wurde an deinen Elternteil gesendet. Du kannst sie widerrufen und eine neue senden.",
        revoked: "Einladung widerrufen",
        conflict: "Einladung existiert bereits, oder du hast schon einen Elternteil"
      },
      shared: {
        title: "Mit mir geteilt",
        empty: "Noch niemand hat eine Wunschliste mit dir geteilt."
      },
      friend: {
        title: "Freunde",
        hint: "Du kannst einen Freund einladen — er bekommt sein eigenes RobTop.",
        invite: "Freund einladen",
        sheetHint: "Dein Freund waehlt einen Nickname (nie den echten Namen!) und bekommt ein eigenes RobTop. Bis ein Elternteil dazukommt, passt dein Elternteil auf das Konto auf.",
        makeLink: "Link erstellen",
        linkReady: "Einladungslink ist bereit:",
        copy: "Kopieren", copied: "Kopiert",
        parentOnly: "Ein Freund braucht erst einen echten oder vorlaeufigen Elternteil.",
        noParent: "Bitte zuerst einen Elternteil einladen."
      },
      helpdesk: {
        ask: "Support kontaktieren",
        title: "Support",
        hint: "Beschreibe kurz, was passiert ist. Ein Erwachsener sieht die Nachricht.",
        ph: "Was ist passiert?",
        send: "Senden", sent: "Gesendet",
        tooMany: "Bitte warte kurz vor der naechsten Nachricht.",
        myTickets: "Meine Anfragen", empty: "Noch keine Anfragen.",
        closed: "geloest", open: "offen",
        you: "Du", support: "RobTop-Team",
        replyPh: "Antwort schreiben…", reply: "Antworten",
        reopenHint: "Eine Antwort oeffnet die Anfrage wieder.",
        solve: "Geloest ✓", solveConfirm: "Problem als geloest markieren?",
        solved: "Als geloest markiert"
      },
      reg: {
        link: "Ich bin ein neuer Elternteil — Familie erstellen",
        nickPh: "Dein Nickname",
        title: "Familie erstellen",
        hint: "Eltern registrieren sich mit E-Mail. Kinder fuegst du danach hinzu; sie brauchen nur einen Nickname.",
        btn: "Familie erstellen",
        fail: "Konnte nicht erstellt werden: E-Mail und Nickname pruefen (vielleicht vergeben)"
      },
      lock: { hint: "Melde dich an, um fortzufahren", title: "Wer meldet sich an?" },
      account: {
        title: "Konto",
        loading: "Wir pruefen, wer angemeldet ist…",
        loginHint: "Eltern melden sich mit E-Mail an, Kinder mit Nickname.",
        loginPh: "E-Mail oder Nickname", passPh: "Passwort",
        signIn: "Anmelden", signOut: "Abmelden",
        roleParent: "Elternteil/Betreuung", roleChild: "Kind",
        badLogin: "Falscher Login oder falsches Passwort",
        changeTitle: "Neues Passwort festlegen",
        changeHint: "Du hast dich mit einem Einmalpasswort angemeldet. Lege dein eigenes Passwort fest, um fortzufahren.",
        newPassPh: "Neues Passwort", saveCont: "Speichern und weiter",
        weakPass: "Mindestens 4 Zeichen",
        demoNote: "Anmeldung funktioniert in der Server-Version der App.",
        welcome: "Willkommen, {name}!", signedOut: "Du bist abgemeldet",
        guestNote: "Ohne Anmeldung laeuft die App im Familienmodus.",
        forgot: "Passwort vergessen?",
        forgotHint: "Nur fuer Eltern: Das Passwort eines Kindes wird vom Elternteil zurueckgesetzt. Gib deine E-Mail ein — wir senden einen Link.",
        forgotSend: "Link senden", forgotSent: "Falls diese E-Mail registriert ist, wurde der Link gesendet.",
        deviceList: "Auf diesem Geraet",
        addAccount: "Konto hinzufuegen",
        addHint: "Einmal anmelden — das Konto bleibt auf diesem Geraet zum schnellen Wechsel.",
        orPassword: "Oder mit Passwort anmelden:",
        switchGone: "Dieses Konto ist nicht mehr verfuegbar — bitte mit Passwort anmelden",
        removeDev: "Von diesem Geraet entfernen",
        removeConfirm: "{name} von diesem Geraet entfernen? Zum Zurueckholen brauchst du das Passwort. Daten bleiben erhalten.",
        removedDev: "{name} wurde von diesem Geraet entfernt"
      },
      store: {
        title: "Apps", adminNote: "App-Verwaltung ist fuer Eltern.",
        installed: "Installiert", installApp: "App installieren",
        pickBundle: "📦 Paket waehlen (.robtop.json)",
        up: "Nach oben", down: "Nach unten", remove: "Entfernen", toggle: "Ein / aus",
        srcInstalled: "installiert", srcBuiltin: "eingebaut", soonSuffix: " · bald",
        installedToast: "Installiert: {name}",
        uninstallTitle: "App entfernen?", uninstallText: "Daten und Ereignisse bleiben erhalten."
      },
      err: {
        install_failed: "Konnte nicht installiert werden", install_error: "Installationsfehler",
        bundle_not_json: "Defektes Paket (kein JSON)",
        bundle_no_manifest: "Paket hat kein manifest/files",
        bad_id: "Ungueltige App-ID",
        server_code_denied: "Server-Code in einem Paket ist nicht erlaubt",
        module_load: "Modul wurde nicht geladen", module_error: "Modulfehler",
        module_open: "“{name}” konnte nicht geoeffnet werden",
        config_missing: "config.php nicht gefunden",
        db_failed: "Datenbankverbindung fehlgeschlagen",
        not_image: "Das ist kein Bild",
        expected_image: "Ein Bild wird erwartet (png/jpg/webp/gif)",
        corrupt_data: "Beschaedigte Daten",
        file_too_big: "Datei ist zu gross",
        save_failed: "Datei konnte nicht gespeichert werden",
        need_manifest: "manifest und files sind erforderlich",
        reserved_id: "Reservierte ID",
        cant_replace_native: "Eine eingebaute App kann nicht ersetzt werden",
        bad_filename: "Ungueltiger Dateiname: {name}",
        bad_type: "Nicht erlaubter Typ: {name}",
        bundle_too_big: "Paket ist zu gross",
        no_module_js: "Paket enthaelt keine module.js",
        no_apps_dir: "Keine Berechtigung fuer den apps-Ordner",
        write_failed: "{name} konnte nicht geschrieben werden",
        cant_uninstall_native: "Eine eingebaute App kann nicht entfernt werden"
      }
    }
  });
})(window.RobTop);
